[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "${{ env.SUPABASE_URL }}"
  VITE_SUPABASE_ANON_KEY = "${{ env.SUPABASE_ANON_KEY }}"

# Redirect all routes to index.html to support SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add CORS headers to allow Supabase connections
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey, X-Client-Info, X-Client-Library, X-Client-Library-Version"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

# For API routes
[[headers]]
  for = "/api/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "credentialless"
    Cross-Origin-Opener-Policy = "cross-origin-isolated"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey, X-Client-Info"